Repository betagouv/mission-transition-ecologique, pull requests merged in 2023-11, with the labels that each got.

#169 PR - Feature: update contact form message
  packages/web/src/components/TeeForm.vue
  packages/web/src/questionnaire/trackResults.ts
  packages/web/src/questionnaire/trackSiret.ts
  packages/web/src/stores/choices.ts
  packages/web/src/types/formTypes.ts
  packages/web/src/utils/helpers.ts
Labels: need validation

#176 PR - Doc: update readme
  README.md
  package-lock.json
  package.json
  packages/backend/.env.example
  packages/data/.env.example
  packages/data/example.env
  packages/web/.env.example
  packages/web/README.md
  packages/web/example.env
  packages/web/images/screenshots/screenshot-2023-10-19.png
  packages/web/public/css/core.main.min.css
Labels: need validation

#203 PR - css and edito corrections on trackSiret + TeeTrackInput
  packages/web/public/css/custom.css
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeTrackInput.vue
  packages/web/src/questionnaire/trackSiret.ts
Labels: enhancement, UX

#212 fix: change arrow position to right on tracks and contact pages
  packages/web/src/components/TeeForm.vue
  packages/web/src/components/TeeTrack.vue
Labels: UX

#201 PR - Add filter(s) to TeeResults component
  packages/web/public/css/core.main.min.css
  packages/web/public/css/custom.css
  packages/web/public/images/tracks/no-results.svg
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeResults.vue
  packages/web/src/components/TeeTrack.vue
  packages/web/src/components/results/TeeNoResults.vue
  packages/web/src/components/results/TeeResults.vue
  packages/web/src/components/results/TeeResultsFilter.vue
  packages/web/src/questionnaire/trackGoals.ts
  packages/web/src/questionnaire/trackResults.ts
  packages/web/src/stores/tracks.ts
  packages/web/src/translations/fr.ts
  packages/web/src/types/otherTypes.ts
  packages/web/src/types/tracksTypes.ts
Labels: enhancement

#135 PR - adding user error callback to form
  packages/web/.env.example
  packages/web/README.md
  packages/web/public/css/custom.css
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeForm.vue
  packages/web/src/questionnaire/trackResults.ts
  packages/web/src/translations/fr.ts
  packages/web/src/types/envTypes.ts
  packages/web/src/types/otherTypes.ts
  packages/web/src/utils/requests.ts
Labels: enhancement, Design UX UI

#221 perf: quick win for filtering programs with publicodes
  packages/backend/src/domain/eligibility.ts
Labels: enhancement, perfs

#270 fix: replace logo mission-transition by a clean one
  packages/web/public/images/logos/mission-transition-logo-alone.png
Labels: dev front

#272 fix: reduce margins and padding around CTA in home page
  packages/web/src/components/home/TeeCta.vue
  packages/web/src/pages/TeeHomePage.vue
Labels: need validation, minor fix, dev front

#275 fix: rename filter labels for objectifs prioritaires
  packages/web/src/questionnaire/trackResults.ts
Labels: valid, minor fix, dev front

#278 Fix/logo mission transition
  packages/web/public/images/logos/mission-transition-logo-alone.png
Labels: minor fix, dev front

#285 Fix/remove banner bottom from pages
  packages/web/src/pages/TeeCatalogPage.vue
  packages/web/src/pages/TeeHomePage.vue
  packages/web/src/pages/TeeQuestionnairePage.vue
  packages/web/src/router/index.ts
  packages/web/src/stores/tracks.ts
Labels: need validation, minor fix, dev front

#297 fix: update link label for accesibilite
  packages/web/src/components/TeeAppFooter.vue
Labels: edito

#306 Fix/responsive 296
  packages/web/public/css/core.main.min.css
  packages/web/public/css/custom.css
  packages/web/src/WidgetApp.ce.vue
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeTrack.vue
  packages/web/src/pages/TeeQuestionnairePage.vue
Labels: bug, minor fix, dev front

#309 fix: resolution issue 303 - edito
  packages/web/src/questionnaire/trackResults.ts
Labels: minor fix, edito

#307 fix: adjust UI and UX on first track + css addons
  packages/web/public/css/custom.css
  packages/web/src/WidgetApp.ce.vue
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeTrack.vue
  packages/web/src/pages/TeeQuestionnairePage.vue
Labels: enhancement, minor fix, dev front

#332 fix: responsive burger is now functional
  packages/web/src/components/TeeHeader.vue
  packages/web/src/types/routeType.ts
Labels: bug, dev front

#227 feat: Mise-à-jour des filtrages des secteurs d'activité (parcours sans siret)
  packages/web/src/types/publicodesObjects.ts
Labels: enhancement
