Repository betagouv/mission-transition-ecologique, pull requests merged in 2023-10, with the labels that each got.

#132 UI & UX fixes
  packages/web/public/css/custom.css
  packages/web/src/TeeApp.ce.vue
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeProgramDetail.vue
  packages/web/src/components/TeeTrack.vue
  packages/web/src/components/TeeTrackInput.vue
  packages/web/src/questionnaire/trackBuildingProperty.ts
  packages/web/src/questionnaire/trackEnergyReduction.ts
  packages/web/src/questionnaire/trackMobility.ts
  packages/web/src/questionnaire/trackNeeds.ts
  packages/web/src/questionnaire/trackStrategyAudits.ts
  packages/web/src/questionnaire/trackWastesStake.ts
  packages/web/src/questionnaire/trackWaterStake.ts
  packages/web/src/translations/fr.ts
Labels: UX

#142 PR - UI fixes
  packages/web/public/css/custom.css
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeProgramDetail.vue
  packages/web/src/components/TeeTrackInput.vue
  packages/web/src/questionnaire/trackEnergyReduction.ts
  packages/web/src/questionnaire/trackMobility.ts
  packages/web/src/questionnaire/trackWastesStake.ts
  packages/web/src/questionnaire/trackWaterStake.ts
Labels: UX

#147 PR - upgrade: fixes d'issues UI/UX (evols suite aux entretiens utilisateurs)
  packages/web/public/css/custom.css
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeForm.vue
  packages/web/src/components/TeeProgramDetail.vue
  packages/web/src/components/TeeTrack.vue
  packages/web/src/questionnaire/trackBuildingProperty.ts
  packages/web/src/questionnaire/trackGoals.ts
  packages/web/src/questionnaire/trackHelp.ts
  packages/web/src/questionnaire/trackNeeds.ts
  packages/web/src/questionnaire/trackResults.ts
  packages/web/src/questionnaire/trackStructureWorkforce.ts
  packages/web/src/questionnaire/trackWastesStake.ts
  packages/web/src/stores/choices.ts
  packages/web/src/translations/fr-operators.ts
  packages/web/src/translations/fr.ts
Labels: UX

#186 PR - feat: add aid info in miniature cards
  packages/web/public/css/custom.css
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeResults.vue
  packages/web/src/types/programTypes.ts
Labels: enhancement

#193 PR- fix: correct BPI label
  packages/web/src/translations/fr-operators.ts
Labels: enhancement

#191 PR - fix: add scrollToTop calls to TeeResults and TeeProgramDetail components
  packages/web/src/TeeApp.ce.vue
  packages/web/src/components/TeeProgramDetail.vue
  packages/web/src/components/TeeResults.vue
  packages/web/src/components/TeeTrack.vue
Labels: bug

#167 PR - Feature: update node from 16 to 18
  .github/workflows/tests.yml
  .nvmrc
  package-lock.json
  package.json
  packages/backend/package.json
  packages/web/package.json
Labels: need validation
