Repository betagouv/mission-transition-ecologique, pull requests merged in 2023-09, with the labels that each got.

#103 🖥️ add illustrations to program details in small tiles at bottom
  packages/web/public/data/output/dataset_out.json
  packages/web/public/data/programs/diag-decarbon-action.yaml
  packages/web/public/data/programs/diag-eco-flux.yaml
  packages/web/public/data/programs/diag-ecoconception.yaml
  packages/web/public/data/programs/fonds-tourisme-durable.yaml
  packages/web/public/data/programs/performa-environnement.yaml
  packages/web/public/data/programs/tpe-gagnantes.yaml
  packages/web/public/data/programs/tremplin.yaml
  packages/web/public/data/programs/visite-energie.yaml
  packages/web/public/images/TEE-cout.svg
  packages/web/public/images/TEE-duree.svg
  packages/web/public/images/TEE-porteur.svg
  packages/web/public/images/TEE-typefinance.svg
  packages/web/src/components/TeeProgram.vue
  packages/web/src/components/TeeProgramDetail.vue
  packages/web/src/components/TeeResults.vue
  packages/web/src/components/TeeTile.vue
  packages/web/src/questionnaire/trackResults.ts
  packages/web/src/translations/fr.ts
  packages/web/src/types/index.ts
Labels: enhancement

#107 hotfix: missing attribute field in brevo form data
  packages/web/src/questionnaire/trackResults.ts
Labels: bug

#111 Validation des données de dispositifs en intégration continue via un json schema
  .github/workflows/test-data.yml
  README.md
  package-lock.json
  packages/backend/data/program-data-schema.json
  packages/backend/package.json
  packages/backend/tests/api-sirene.test.ts
  packages/backend/tests/test-program-data.sh
Labels: enhancement

#114 New program fields : schema > data > typescript > components
  packages/backend/data/program-data-schema.json
  packages/web/public/data/output/dataset_out.json
  packages/web/public/data/programs/diag-decarbon-action.yaml
  packages/web/public/data/programs/diag-eco-flux.yaml
  packages/web/public/data/programs/diag-ecoconception.yaml
  packages/web/public/data/programs/fonds-tourisme-durable.yaml
  packages/web/public/data/programs/performa-environnement.yaml
  packages/web/public/data/programs/tpe-gagnantes.yaml
  packages/web/public/data/programs/tremplin.yaml
  packages/web/public/data/programs/visite-energie.yaml
  packages/web/src/components/TeeProgram.vue
  packages/web/src/components/TeeProgramDetail.vue
  packages/web/src/components/TeeResults.vue
  packages/web/src/translations/fr.ts
  packages/web/src/types/envTypes.ts
  packages/web/src/types/formTypes.ts
  packages/web/src/types/index.ts
  packages/web/src/types/otherTypes.ts
  packages/web/src/types/programTypes.ts
  packages/web/src/types/tracksTypes.ts
  packages/web/src/types/translationTypes.ts
  packages/web/src/utils/conditions.ts
Labels: enhancement

#110 Front issue 108 : new tracks and regroup questions by categories in sidebar
  packages/web/index.html
  packages/web/public/css/custom.css
  packages/web/public/data/output/dataset_out.json
  packages/web/public/data/programs/visite-energie.yaml
  packages/web/public/images/thema/thema-batiments.svg
  packages/web/public/images/thema/thema-dechets.svg
  packages/web/public/images/thema/thema-eau.svg
  packages/web/public/images/thema/thema-energie.svg
  packages/web/public/images/thema/thema-mobilite.svg
  packages/web/public/images/tracks/j-ai-un-obectif.svg
  packages/web/public/images/tracks/je-ne-sais-pas-par-ou-commencer.svg
  packages/web/src/TeeApp.ce.vue
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeForm.vue
  packages/web/src/components/TeeProgramDetail.vue
  packages/web/src/components/TeeResults.vue
  packages/web/src/components/TeeSidebar.vue
  packages/web/src/components/TeeTrack.vue
  packages/web/src/components/TeeTrackButtonInput.vue
  packages/web/src/components/TeeTrackInput.vue
  packages/web/src/questionnaire/index.ts
  packages/web/src/questionnaire/trackBuildingProperty.ts
  packages/web/src/questionnaire/trackBuildingSurface.ts
  packages/web/src/questionnaire/trackEnergyStake.ts
  packages/web/src/questionnaire/trackGoals.ts
  packages/web/src/questionnaire/trackHelp.ts
  packages/web/src/questionnaire/trackMobility.ts
  packages/web/src/questionnaire/trackMobilityEnergy.ts
  packages/web/src/questionnaire/trackMobilityNumberVehicles.ts
  packages/web/src/questionnaire/trackNeeds.ts
  packages/web/src/questionnaire/trackResults.ts
  packages/web/src/questionnaire/trackRoles.ts
  packages/web/src/questionnaire/trackSectors.ts
  packages/web/src/questionnaire/trackSiret.ts
  packages/web/src/questionnaire/trackStrategyAudits.ts
  packages/web/src/questionnaire/trackStrategyAuditsSelect.ts
  packages/web/src/questionnaire/trackStructureSizes.ts
  packages/web/src/questionnaire/trackStructureWorkforce.ts
  packages/web/src/questionnaire/trackWastesMaterials.ts
  packages/web/src/questionnaire/trackWastesSorting.ts
  packages/web/src/questionnaire/trackWastesStake.ts
  packages/web/src/questionnaire/trackWaterStake.ts
  packages/web/src/stores/programs.ts
  packages/web/src/stores/tracks.ts
  packages/web/src/translations/fr.ts
  packages/web/src/types/index.ts
  packages/web/src/types/otherTypes.ts
  packages/web/src/types/programTypes.ts
  packages/web/src/types/tracksTypes.ts
  packages/web/src/utils/conditions.ts
  packages/web/src/utils/helpers.ts
  packages/web/src/utils/requests.ts
Labels: enhancement

#119 fix messages and texts in tracks + inject data into form's text-area
  packages/web/public/css/custom.css
  packages/web/public/images/thema/thema-strategie.svg
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeForm.vue
  packages/web/src/components/TeeProgramDetail.vue
  packages/web/src/questionnaire/index.ts
  packages/web/src/questionnaire/trackEnergyReduction.ts
  packages/web/src/questionnaire/trackEnergyTypes.ts
  packages/web/src/questionnaire/trackGoals.ts
  packages/web/src/questionnaire/trackHelp.ts
  packages/web/src/questionnaire/trackMobilityNumberVehicles.ts
  packages/web/src/questionnaire/trackResults.ts
  packages/web/src/questionnaire/trackSectors.ts
  packages/web/src/questionnaire/trackStrategyAudits.ts
  packages/web/src/questionnaire/trackWastesMaterials.ts
  packages/web/src/questionnaire/trackWastesSorting.ts
  packages/web/src/questionnaire/trackWastesStake.ts
  packages/web/src/questionnaire/trackWaterStake.ts
  packages/web/src/translations/fr.ts
  packages/web/src/types/formTypes.ts
  packages/web/src/types/otherTypes.ts
  packages/web/src/utils/helpers.ts
Labels: enhancement, track

#120 fix: debug back to track keeping user's selection within track component
  packages/web/src/components/TeeSidebar.vue
  packages/web/src/components/TeeTrack.vue
  packages/web/src/stores/tracks.ts
Labels: bug

#101 ⚙️ upgrade: first round trying to implement a Brevo post endpoint (cf #53)
  packages/backend/example.env
  packages/backend/src/controller/contactsController.ts
  packages/backend/src/controller/etablissementsController.ts
  packages/backend/src/controller/healthController.ts
  packages/backend/src/controller/types.ts
  packages/backend/src/domain/api.ts
  packages/backend/src/domain/features.ts
  packages/backend/src/domain/spi.ts
  packages/backend/src/domain/types.ts
  packages/backend/src/infrastructure/brevo-API.ts
  packages/backend/src/infrastructure/sirene-API.ts
  packages/backend/src/infrastructure/types.ts
  packages/web/example.env
  packages/web/src/questionnaire/trackResults.ts
Labels: enhancement
