Repository betagouv/mission-transition-ecologique, pull requests merged in 2023-12, with the labels that each got.

#378 fix: remove vscode folder + update gitignore
  .gitignore
  packages/web/.vscode/extensions.json
Labels: tech-only

#363 fix: change main label of track wastes question
  packages/web/src/questionnaire/trackWastesMaterials.ts
Labels: need validation, minor fix, edito

#374 feat: tri simple des programmes
  packages/backend/src/domain/filter-programs.ts
  packages/backend/src/domain/sort-programs.ts
  packages/backend/tests/filter-programs.test.ts
  packages/backend/tests/sort-programs.test.ts
  packages/backend/tests/testing.ts
  packages/web/src/stores/programs.ts
Labels: enhancement
