Repository betagouv/mission-transition-ecologique, pull requests merged in 2024-02, with the labels that each got.

#526 add thumbnail meta to index.html
  packages/web/index.html
  packages/web/public/images/TEE-preview-image-529-by-298.png
  packages/web/public/images/TEE-preview-image.png
Labels: minor fix, dev front

#567 accordion component w/ slot for both eligibility and long description in detail page
  packages/web/public/css/custom.css
  packages/web/src/assets/custom.css
  packages/web/src/components/program/ProgramAccordion.vue
  packages/web/src/components/program/ProgramEligibility.vue
  packages/web/src/components/program/ProgramLongDescription.vue
  packages/web/src/components/program/TeeProgramDetail.vue
Labels: dev front

#566 Fix/UI spacings 447
  packages/web/src/components/program/ProgramObjective.vue
  packages/web/src/components/program/TeeProgramDetail.vue
  packages/web/src/pages/TeeCatalogPage.vue
  packages/web/src/pages/TeeQuestionnairePage.vue
Labels: dev front

#569 Fix/UI responsive 274
  packages/web/public/css/custom.css
  packages/web/public/images/TEE-cout-02.svg
  packages/web/public/images/TEE-porteur.png
  packages/web/public/images/TEE-porteur.svg
  packages/web/public/images/TEE_eolienne-mini.svg
  packages/web/public/images/home/building-solo.svg
  packages/web/public/images/home/electric-solo.svg
  packages/web/public/images/home/mobility-solo.svg
  packages/web/public/images/home/water-solo.svg
  packages/web/src/assets/custom.css
  packages/web/src/components/TeeQuestionnaire.vue
  packages/web/src/components/TeeTile.vue
  packages/web/src/components/home/TeeCta.vue
  packages/web/src/components/home/TeeHomeInfos.vue
  packages/web/src/components/home/TeeHomeSteps.vue
  packages/web/src/components/program/TeeProgramDetail.vue
  packages/web/src/components/results/TeeResults.vue
  packages/web/src/components/tracks/TeeTrack.vue
  packages/web/src/pages/TeeCatalogPage.vue
  packages/web/src/pages/TeeHomePage.vue
  packages/web/src/pages/TeeQuestionnairePage.vue
Labels: dev front

#591 fix(router): redirect page not found
  packages/web/src/router/index.ts
Labels: minor fix
