Repository betagouv/mission-transition-ecologique, pull requests merged in 2024-01, with the labels that each got.

#436 feat: add new component ProgramLongDescription for detailled card
  package-lock.json
  packages/web/src/components/program/ProgramLongDescription.vue
  packages/web/src/components/program/TeeProgramDetail.vue
  packages/web/src/translations/fr.ts
Labels: dev front

#422 Refactor/lint attributes per line 406
  .eslintrc.js
  .prettierrc.json
  package-lock.json
  package.json
  packages/web/.eslintrc.js
  packages/web/src/WidgetApp.ce.vue
  packages/web/src/components/TeeCredits.vue
  packages/web/src/components/TeeFooter.vue
  packages/web/src/components/TeeForm.vue
  packages/web/src/components/TeeMatomo.vue
  packages/web/src/components/TeeSidebar.vue
  packages/web/src/components/TeeTile.vue
  packages/web/src/components/button/DsfrButton.vue
  packages/web/src/components/contact/ContactButton.vue
  packages/web/src/components/home/TeeContact.vue
  packages/web/src/components/home/TeeCta.vue
  packages/web/src/components/home/TeeHomeInfos.vue
  packages/web/src/components/home/TeeHomeSteps.vue
  packages/web/src/components/program/ProgramEligibility.vue
  packages/web/src/components/program/ProgramLongDescription.vue
  packages/web/src/components/program/ProgramObjective.vue
  packages/web/src/components/program/TeeProgramDetail.vue
  packages/web/src/components/results/TeeNoResults.vue
  packages/web/src/components/results/TeeResults.vue
  packages/web/src/components/results/TeeResultsFilter.vue
  packages/web/src/components/tracks/TeeTrack.vue
  packages/web/src/components/tracks/TeeTrackButtonInput.vue
  packages/web/src/components/tracks/TeeTrackInput.vue
  packages/web/src/components/tracks/TeeTrackSelect.vue
  packages/web/src/pages/TeeAccessibilityPage.vue
  packages/web/src/pages/TeeCatalogPage.vue
  packages/web/src/pages/TeeHomePage.vue
  packages/web/src/pages/TeeLegalPage.vue
  packages/web/src/pages/TeePersonalDataPage.vue
  packages/web/src/pages/TeeProgramPage.vue
  packages/web/src/pages/TeeQuestionnairePage.vue
Labels: tech-only

#517 fix(dependabot): update package security
  .eslintrc.js
  package-lock.json
  packages/backend/package.json
  packages/web/.eslintrc.cjs
  packages/web/netlify.toml
  packages/web/package.json
  packages/web/vitest.config.ts
Labels: dependencies

#514 feat(security): add security headers
  README.md
  packages/web/index.html
  packages/web/vite.config.ts
  scalingo.json
Labels: DevOps

#525 new cma logo (png) + update link in footer
  packages/web/public/images/logos/cma-france.png
  packages/web/src/components/TeeFooter.vue
Labels: minor fix, dev front

#486 feat: program availability's end date
  packages/web/public/css/custom.css
  packages/web/src/assets/custom.css
  packages/web/src/components/program/TeeProgramDetail.vue
  packages/web/src/translations/fr.ts
  packages/web/src/utils/program.ts
Labels: dev front

#524 UI fixes
  packages/web/src/questionnaire/trackStrategyAuditsSelect.ts
Labels: minor fix, dev front
